### ISSUE TITLE
Uremiyor

### ISSUE THREAD

**Issue by oganm** [ilimugur/yapaybeyan.at#1]
Sitenin kodu yok ortalarda oraya koyamadim. Ama kullanmaya calistigimda konsol su uyariyi veriyor: `"error found:Unexpected token o in JSON at position 1"`

**Comment by ilimugur** [comment]
Ustunden hayli zaman gecmis, ancak goruyorum; ama calistirmakta kullandigin komutu, komutlari hatirliyor musun? char-rnn'i ve onun calismasi icin gereken diger tool'lari kurmakta sorun yasamis miydin? Eger yukleme sirasinda hicbir hatayla karsilasmamissan en olasi olan sey, bu hatayla bir encoding sorunu nedeniyle karsilasiyor olman. Kullandigin parametrelere dair daha ayrintili bilgi verebilirsen bakmaya calisabilirim.

**Comment by oganm** [comment]
Hatirlamiyorum o zamanlar ne yapmistim da su an sorun yok gibi gozukuyor.
